// This file is generated by Astro DB
declare module 'astro:db' {
    import { Table } from 'rethinkdb-ts';
    
    export const Album: Table<{
        id: string;
        title: string;
        color: string;
        cover: string;
    }>;
    
    export const Artist: Table<{
        id: string;
        name: string;
        cover: string;
    }>;
    
    export const Song: Table<{
        id: string;
        title: string;
        albumId: string;
        image: string;
        duration: number;
    }>;
    
    export const SongArtists: Table<{
        songId: string;
        artistId: string;
    }>;
}
