// This file is generated by Astro DB
declare module 'astro:db' {
	export const Album: import("@astrojs/db/runtime").Table<
		"Album",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Album","primaryKey":true}},"title":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"title","collection":"Album","primaryKey":false,"optional":false}},"color":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"color","collection":"Album","primaryKey":false,"optional":false}},"cover":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"cover","collection":"Album","primaryKey":false,"optional":false}}}
	>;
	export const Artist: import("@astrojs/db/runtime").Table<
		"Artist",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Artist","primaryKey":true}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Artist","primaryKey":false,"optional":false}},"cover":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"cover","collection":"Artist","primaryKey":false,"optional":false}}}
	>;
	export const Song: import("@astrojs/db/runtime").Table<
		"Song",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Song","primaryKey":true}},"title":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"title","collection":"Song","primaryKey":false,"optional":false}},"albumId":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"albumId","collection":"Song","primaryKey":false,"optional":false}},"image":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"image","collection":"Song","primaryKey":false,"optional":false}},"duration":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"duration","collection":"Song","primaryKey":false,"optional":false}}}
	>;
	export const SongArtists: import("@astrojs/db/runtime").Table<
		"SongArtists",
		{"songId":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"songId","collection":"SongArtists","primaryKey":false,"optional":false}},"artistId":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"artistId","collection":"SongArtists","primaryKey":false,"optional":false}}}
	>;
}
